# permissions for end users to edit volumegroupsnapshotcontents.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: volumegroupsnapshotcontent-editor-role
rules:
- apiGroups:
  - volumegroup.example.com
  resources:
  - volumegroupsnapshotcontents
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - volumegroup.example.com
  resources:
  - volumegroupsnapshotcontents/status
  verbs:
  - get
