# permissions for end users to view volumegroupsnapshotcontents.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: volumegroupsnapshotcontent-viewer-role
rules:
- apiGroups:
  - volumegroup.example.com
  resources:
  - volumegroupsnapshotcontents
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - volumegroup.example.com
  resources:
  - volumegroupsnapshotcontents/status
  verbs:
  - get
