# permissions for end users to view volumegroupsnapshots.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: volumegroupsnapshot-viewer-role
rules:
- apiGroups:
  - volumegroup.example.com
  resources:
  - volumegroupsnapshots
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - volumegroup.example.com
  resources:
  - volumegroupsnapshots/status
  verbs:
  - get
