# permissions for end users to view volumegroups.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: volumegroup-viewer-role
rules:
- apiGroups:
  - volumegroup.example.com
  resources:
  - volumegroups
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - volumegroup.example.com
  resources:
  - volumegroups/status
  verbs:
  - get
