# permissions for end users to edit volumegroups.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: volumegroup-editor-role
rules:
- apiGroups:
  - volumegroup.example.com
  resources:
  - volumegroups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - volumegroup.example.com
  resources:
  - volumegroups/status
  verbs:
  - get
